# A deployment is responsible for keeping a set of pods running.
# For reference, template taken from "https://gist.github.com/matthewpalmer/3a63fc20ecbf5d82ffe5bf1a8ec968ac"


kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: comments-v1-deployment
spec:
 
  # 1. How many copies of each pod do we want?
  replicas: 3

  # 2. How do want to update the pods?
  strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: example
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
