# This compose is for testing purposes only, as it runs tests as a service.
version: '3.7'


volumes:
  db-storage:
  rabbitmq-data:
  
services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped
  
  database:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  app:
    build: ..
    ports:
      - 5000:5000
    depends_on:
      - database
      - rabbitmq
    environment: 
      - RABBITMQ_USERNAME=${RABBITMQ_PASSWORD}
      - RABBITMQ_PASSWORD=${RABBITMQ_USERNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    
  test:
    build: ../src
    depends_on:
      - app
      - database
      - rabbitmq
    environment: 
      - RABBITMQ_USERNAME=${RABBITMQ_PASSWORD}
      - RABBITMQ_PASSWORD=${RABBITMQ_USERNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
