# This compose is for testing purposes only, as it runs tests as a service.
version: '3.7'


volumes:
  db_data:
  rabbitmq-data:
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    restart: unless-stopped

  mySQL:
    image: mysql:8
    container_name: comment_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
    restart: unless-stopped

  app:
    build: ..
    ports:
      - 5000:5000
    depends_on:
      - mySQL
      - rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    restart: unless-stopped
    
  test:
    build: ../src
    depends_on:
      - mySQL
      - rabbitmq
      - app
    environment: 
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    restart: unless-stopped
