# This compose is for testing purposes only, as it runs tests as a service.
version: '3.7'


volumes:
  db-storage:
  rabbitmq-data:
  
services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    restart: unless-stopped
  
  database:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-storage:/var/lib/postgresql/data
    env_file: ../.devcontainer/database.conf
    restart: unless-stopped

  app:
    build: ..
    ports:
      - 5000:5000
    depends_on:
      - database
      - rabbitmq
    restart: unless-stopped
    
  test:
    build: ../src
    depends_on:
      - app
      - database
      - rabbitmq
