version: '3.7'


volumes:
  rabbitmq-data:
  db_data:

services:
  vscode:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      #- ..:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: 'Europe/Copenhagen'
      #- DATABASE_CONN_URI=postgres@database:5432/postgress
      #- RABBITMQ_CONN_URI=amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    restart: unless-stopped

  mySQL:
    image: mysql:8
    container_name: comment_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306
    restart: unless-stopped

  app:
    build: ..
    ports:
      - 5000:5000
    depends_on:
      - mySQL
      - rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      MYSQL_DATABASE: 'commentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    restart: unless-stopped
