version: '3.7'


volumes:
  db-storage:
  rabbitmq-data:


services:
  vscode:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      #- ..:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Copenhagen
      #- DATABASE_CONN_URI=postgres@database:5432/postgress
      #- RABBITMQ_CONN_URI=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_USERNAME=${RABBITMQ_PASSWORD}
      - RABBITMQ_PASSWORD=${RABBITMQ_USERNAME}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    restart: unless-stopped


  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped
  
  database:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  app:
    build: ..
    ports:
      - 5000:5000
    depends_on:
      - database
      - rabbitmq
    environment: 
      - RABBITMQ_USERNAME=${RABBITMQ_PASSWORD}
      - RABBITMQ_PASSWORD=${RABBITMQ_USERNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped