import os

USER = os.environ['MYSQL_USER']
PASSWORD = os.environ['MYSQL_PASSWORD']
HOST = os.environ['MYSQL_HOST']
DATABASE = os.environ['MYSQL_DATABASE']
DATABASE_CONNECTION_URI = f'mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}:3306/{DATABASE}'

AMQP_USER = PORT = os.environ['RABBITMQ_DEFAULT_USER']
AMQP_PASSWORD = os.environ['RABBITMQ_DEFAULT_PASS']
AMQP_URI = f"amqp://{AMQP_USER}:{AMQP_PASSWORD}@rabbitmq:5432/"