name: Build docker-compose, runs test, and pushes to dockerhub
on: push
jobs:
  test:
    name: Build docker-compose, and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build compose
      run: docker-compose -f dev-compose.yaml up -d
    - name: Run tests
      run: docker-compose -f dev-compose.yaml run test
      
  push_to_registry:
    needs: [test]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: imagehostmad/comments
          tag_with_ref: true
