name: Build docker-compose and run tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build compose
      run: docker-compose -f dev-compose.yaml up -d
    - name: Run tests
      run: docker-compose -f dev-compose.yaml run test
